### ISSUE TITLE
Cannot find module './FileUtils'

### ISSUE THREAD

**Issue by Eusse** [concon121/atom-maven#11]
Steps to reproduce:
1. Install via package manager

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package, v0.5.0
### Stack Trace

Failed to load the atom-maven package

```
At Cannot find module './FileUtils'

Error: Cannot find module './FileUtils'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ahernandeze/.atom/packages/atom-maven/lib/atom-maven.js:12:13)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:743:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
autocomplete-java, v1.2.5
atom-maven, v0.5.0
linter, v1.11.4
linter-javac, v1.9.1
merge-conflicts, v1.4.2
minimap, v4.23.5
pigments, v0.26.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by concon121** [comment]
Hi Eusse, I've released a new update 0.6.0 and tested installing via the package manager and it seems to start up fine for me.  Please can you re-test and confirm for me?

Note: I've had to remove the functionality to set up the classpath on start up, so you need to save you pom files for it to generate the .classpath file - i'll be looking to add this back in later this week.

**Comment by Eusse** [comment]
Hi @concon121,
I am getting the same error. I tried installing plugin using apm and the package manager in settings.
This is the output in console using `apm install atom-maven`:
`Installing atom-maven to ~/.atom/packages ✓`

This is the output in atom:

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package, v0.7.0

### Stack Trace

Failed to load the atom-maven package

```
At Cannot find module './FileUtils'

Error: Cannot find module './FileUtils'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ahernandeze/.atom/packages/atom-maven/lib/atom-maven.js:12:13)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
autocomplete-java, v1.2.5
atom-maven, v0.7.0
file-icons, v1.7.11
linter, v1.11.4
linter-javac, v1.9.1
merge-conflicts, v1.4.2
minimap, v4.23.5
pigments, v0.26.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

Is there a dependency missing or outdated?

**Comment by concon121** [comment]
Nah,  FileUtils is a js file which comes bundled with atom-maven,  and the dependencies I used should be downloaded via apm / npm when you download update the package (which you can check by going to $home/. atom/packages/atom-maven/node_modules and cross referencing with package.json)

Admittedly I haven't tested this on a Linux enviomronment,  maybe something behaves differently to windows which hasn't been accounted for? 

I will attempt to replicate your environment tomorrow morning. 

Cheers!
