### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by nickbreen** [concon121/atom-maven#36]
[Enter steps to reproduce below:]
1. run `atom .` on command line
2. error occurs

Additionally the erroneous message "Maven has not been found on the PATH, please ensure that Maven has been installed." displays.

```
$ mvn -v
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-22-generic", arch: "amd64", family: "unix"
```

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package, v0.11.0
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At events.js:141

TypeError: Cannot read property '0' of undefined
    at Object.getGAVT (/home/nick/.atom/packages/atom-maven/lib/maven-utils.js:156:65)
    at /home/nick/.atom/packages/atom-maven/lib/pom-factory.js:62:46
    at Parser.<anonymous> (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/lib/xml2js.js:503:31)
    at Parser.parseString (/home/nick/.atom/packages/atom-maven/node_modules/xml2js/lib/xml2js.js:7:59)
    at fs.readFile (/home/nick/.atom/packages/atom-maven/lib/pom-factory.js:56:14)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-maven, v0.11.0

# Dev
No dev packages
```

**Comment by concon121** [comment]
Thanks for raising this.  There are two action points:
1. If a maven installation can not be found, exit rather than trying to continue to read from things which don't exist.
2. A Maven installation hasn't been found when it clearly exists, this needs to be addressed.

Making an educated guess, are your Maven environment variables set up something like:

```
export M2_HOME=/usr/share/maven
export PATH=$PATH:$M2_HOME/bin"
```

Or if not can you share how you have set up maven to be on your PATH?

Thanks!

**Comment by concon121** [comment]
Released a fix for this issue, please let me know if it resolves your problem.

**Comment by nickbreen** [comment]
Hi
Sorry for not replying earlier.

Relevant environment variables:

$ which mvn
/usr/bin/mvn
$ echo $PATH
/home/nick/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ echo $M2_HOME
/usr/share/maven

Maven 3.3.9 was installed with the universe package if that's relevant.

I'll update and test...

Thanks,

Nick

Nick Breen
foo//bar web development
http://foobar.net.nz
+64 21 410 308

**Comment by concon121** [comment]
Further improvements for this issue in the upcoming release.

Thanks for contributing!
