### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by concon121** [concon121/atom-maven#7]
[Enter steps to reproduce below:]
1. Install via apm

**Atom Version**: 1.7.3
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package, v0.2.0
### Stack Trace

Failed to load the atom-maven package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at MavenUtils (C:\Users\cbr097\.atom\packages\atom-maven\lib\mavenUtils.js:3:10)
    at Object.<anonymous> (C:\Users\cbr097\.atom\packages\atom-maven\lib\mavenUtils.js:114:18)
    at Module._compile (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/cbr097/.atom/packages/atom-maven/lib/atom-maven.js:10:14)
    at Module._compile (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\cbr097\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "nuclide"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-maven, v0.2.0
autocomplete-java, v1.2.5
linter, v1.11.4
linter-javac, v1.9.1
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by concon121** [comment]
atom didn't download npm dependencies when it installed the package, need to investigate this.

**Comment by concon121** [comment]
Tested at home with new update 0.6.0 and this problem seems to have been resolved, will re-test tomorrow on another pc.
