### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Workspace/...

### ISSUE THREAD

**Issue by BuZZ-dEE** [concon121/atom-maven#74]
**Atom**: 1.14.4 x64
**Electron**: 1.4.15
**OS**: linux 4.9.11-1-ARCH
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/path/to/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/path/to/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:47:27
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:68:4
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:21.9.0 python-tools:show-usages (span.syntax--entity.syntax--name.syntax--function.syntax--java)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
angularjs 0.4.0 
atom-arc-ui 1.1.0 
atom-autocomplete-php 0.22.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.29.17 
dojo-snippets 1.0.0 
atom-easy-jsdoc 4.10.0 
atom-maven 1.1.0 
atom-ternjs 0.18.1 
atom-typescript 10.1.14 
autocomplete-java 1.2.5 
autocomplete-jsp 1.2.0 
autocomplete-python 1.8.57 
autocomplete-ruby 0.2.6 
color-picker 2.2.5 
cursor-history 0.9.1 
emmet 2.4.3 
git-blame 0.4.11 
git-plus 7.3.3 
git-time-machine 1.5.6 
highlight-selected 0.12.0 
jquery-snippets 11.0.0 
js-refactor 0.7.5 
language-fish-shell 1.0.5 
language-svg 0.9.4 
last-cursor-position 0.9.0 
linter 1.11.23 
linter-checkstyle 1.2.0 
linter-csslint 1.3.4 
linter-javac 1.9.4 
linter-jshint 3.0.2 
linter-php 1.3.1 
linter-ruby 1.2.5 
linter-scss-lint 3.1.0 
linter-shellcheck 1.4.3 
linter-tslint 0.14.0 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
open-file-in 1.2.3 
pigments 0.39.0 
print-atom 0.1.1 
project-manager 3.3.3 
python-debugger 0.2.0 
python-indent 1.0.0 
python-isort 0.0.7 
python-tools 0.6.9 
refactor 0.11.3 
remote-edit2 3.0.0 
split-diff 1.2.0 
svg-preview 0.11.0 
svgo 2.6.0 
svn 0.0.13 
symbols-tree-view 0.13.2 
sync-settings 0.8.1 
syntaxdb-atom-plugin 1.0.3 
term3 0.22.1 
uglify 1.3.1 
```

**Comment by concon121** [comment]
@BuZZ-dEE please can you confirm if this is still an issue in the new releases?  If so, please can you provide some information on how to reproduce the issue?

**Comment by BuZZ-dEE** [comment]
Hi, I let you know in the next days.

Am 16. April 2017 12:53:07 MESZ schrieb Connor Bray <notifications@github.com>:
>Please can you confirm if this is still an issue in the new releases? 
>If so, please can you provide some information on how to reproduce the
>issue?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/concon121/atom-maven/issues/74#issuecomment-294345600

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by concon121** [comment]
Closing due to no response from reporter.
