### ISSUE TITLE
Failed to load the atom-maven package

### ISSUE THREAD

**Issue by phasenraum2010** [concon121/atom-maven#75]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-dev-2e72f39 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.1.0

### Stack Trace

Failed to load the atom-maven package

```
At Identifier 'process' has already been declared

SyntaxError: Identifier 'process' has already been declared
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (atom-maven.js:4:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-maven 1.1.0 
atom-symfony2 0.2.1 
atom-ternjs 0.18.2 
atom-wordpress 0.3.0 
atom-zurb-foundation 2.0.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-wordpress-hooks 0.2.2 
cdn-libs 0.1.2 
composer 0.5.0 
docker 0.7.0 
drupal 1.9.0 
foundation5-snippets 0.2.2 
gitignore-snippets 0.2.5 
jquery-snippets 11.0.0 
language-ansible 0.2.1 
language-chef 0.9.0 
language-docker 1.1.7 
language-sql-mysql 0.3.1 
language-typoscript 0.1.0 
laravel 0.7.1 
php-cs-fixer 4.1.0 
typo3-fluid-atom-snippets 1.2.0 
typo3-fluid-snippets 0.1.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.1.4 
wordpress-suite 0.4.5 
```

**Comment by blassmegod** [comment]
It works with Atom 1.15.0 x64, but on beta x32/x64 it doesn't work, I have same error.

**Comment by concon121** [comment]
Works for me in atom version 1.17.0-beta2, please can you confirm is this issue is resolved?

**Comment by concon121** [comment]
Closing due to no response from reporter.
