### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by brunoobatista** [concon121/atom-maven#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/lecad101/Downloads/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/home/lecad101/Downloads/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:47:27
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:68:4
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-maven 1.1.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.5 
busy-signal 1.3.0 
git-plus 7.3.3 
highlight-selected 0.12.0 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.2.1 
minimap 4.26.8 
pigments 0.39.1 
rest-client 1.3.1 
seti-ui 1.7.0 
terminal-plus 0.14.5 
```

**Comment by brunexmg** [comment]
Postei sem saber.
