### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filePath' of null

### ISSUE THREAD

**Issue by axitdn** [concon121/atom-maven#82]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.3
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'filePath' of null

```
At /Users/nguyenngoctu/.atom/packages/atom-maven/lib/atom-maven.js:49

TypeError: Cannot read property 'filePath' of null
    at /packages/atom-maven/lib/atom-maven.js:49:16
    at didError (/app.asar/src/workspace.js:1260:18)
    at /app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:08.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  7x -2:01.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:11.7.0 core:select-down (input.hidden-input)
  2x -0:11 core:select-up (input.hidden-input)
     -0:08.9.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
atom-beautify 0.29.23 
atom-html-preview 0.1.22 
atom-maven 1.2.1 
atom-react-native-autocomplete 0.0.27 
atom-typescript 11.0.2 
autocomplete-java 1.2.5 
build 0.67.0 
build-gradle 0.6.0 
build-processing 0.1.2 
build-rscript 0.6.1 
build-tools 4.5.9 
build-tsc 0.7.1 
busy 0.7.0 
busy-signal 1.3.0 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.3 
git-time-machine 1.5.9 
impress 0.1.1 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
language-latex 1.0.0 
language-markdown 0.21.0 
language-scala 1.1.8 
latex 0.43.0 
latexer 0.3.0 
linter 2.1.4 
linter-javac 1.9.4 
linter-sass-lint 1.7.4 
linter-tslint 1.1.0 
linter-ui-default 1.2.3 
markdown-writer 2.6.4 
minimap 4.27.1 
multi-cursor 2.1.5 
open-recent 5.0.0 
platformio-ide-terminal 2.5.0 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
scroll-searcher 5.2.0 
show-invisibles-plus 0.3.1 
softcover 0.1.0 
synced-sidebar 0.4.3 
Termrk 1.0.0 
webbox-color 0.5.9 
wordcount 2.10.4 
```

**Comment by concon121** [comment]
This is an odd one.  The filePath property is being retrieved from matches from atom.workspace.scan and a match from the scan can't really be null because thats just no match and so theres nothing to do.

Did you do anything special to get this sort of issue?

**Comment by BuZZ-dEE** [comment]
I can confirm this bug.

**Comment by larrydalaw** [comment]
can i re-do the scan ? i have just updated mvn and jdk

**Comment by larrydalaw** [comment]
uninstall and reinstall the mvn atom package doesnt help

**Comment by codewheeney** [comment]
I've started seeing this just now, OSX 10.14.6 (Mojave), Atom 1.47.0 x64

Electron: 5.0.13
Chrome: 73.0.3683.121
Node: v12.0.0

It appears happens twice on startup.

```
Uncaught TypeError: Cannot read property 'filePath' of null

/Users/jcassidy/.atom/packages/atom-maven/lib/atom-maven.js:64
Hide Stack Trace
TypeError: Cannot read property 'filePath' of null
    at /Users/jcassidy/.atom/packages/atom-maven/lib/atom-maven.js:64:17
    at didError (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:440314)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43716
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202691)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42817)
    at ChildProcess.emit (events.js:194:13)
    at emit (internal/child_process.js:847:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
The error was thrown from the atom-maven package. This issue has already been reported.
```
