### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by marcoslhc** [concon121/atom-maven#83]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.2.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/--------/---------/projects/java2/lesson8/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/----------/-----------/projects/java2/lesson8/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
.bin undefined 
apathy-theme 1.10.6 
atom-beautify 0.29.17 
atom-django 0.3.2 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-maven 1.2.1 
autocomplete-java 1.2.5 
color-picker 2.2.5 
django-templates 0.5.0 
editorconfig 2.2.1 
emmet 2.4.3 
fizzy 0.21.0 
git-log 0.4.1 
git-plus 7.3.0 
git-tab-status 1.9.2 
ink 0.6.3 
isotope-ui 2.7.1 
language-assembly 0.7.1 
language-lisp 0.2.0 
language-matlab 0.2.1 
language-nunjucks 4.1.0 
language-rust 0.4.9 
language-viml 1.1.3 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-csslint 1.3.3 
linter-eslint 8.1.2 
linter-flake8 2.1.4 
linter-javac 1.9.4 
linter-jscs 4.1.1 
linter-jshint 3.0.2 
linter-python-pep8 0.2.0 
linter-scss-lint 3.1.0 
merge-conflicts 1.4.4 
monokai 0.22.0 
newton-dark-syntax 1.1.7 
newton-dark-ui 1.1.2 
node-debugger 1.10.0 
northem-dark-atom-ui 2.0.0 
oceanic-reef-syntax 0.6.0 
one-o-eight-syntax 0.23.2 
Parinfer 1.17.0 
pigments 0.39.0 
pretty-json 1.6.1 
proto-repl 1.4.14 
proto-repl-charts 0.4.0 
react 0.16.2 
remote-sync 4.1.5 
seti-syntax 1.1.2 
seti-ui 1.6.1 
solarized-dark-ui 0.3.2 
sort-lines 0.14.0 
symbols-tree-view 0.13.2 
tabasco 0.5.0 
tesla-atom 4.0.0 
```

**Comment by concon121** [comment]
If you open up the developer tools and have a look at the console, does Maven log any failures which may explain why this happened?

**Comment by concon121** [comment]
And to ask the obvious question, does the file actually exist?

**Comment by binhonglee** [comment]
**UPDATE** : I was dumb. Did not have maven installed in this machine. Installing maven fixed this issue for me.

---

Not OP (obviously) but I have a similar (if not same) problem. I opened up a project that uses pom.xml instead of effective.pom and was thrown the same error. So to answer your question, the file **does not exist**.

I've attached my stack trace below:
`Uncaught Error: ENOENT: no such file or directory, open './effective.pom'`

```
At fs.js:640

Error: ENOENT: no such file or directory, open './effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by concon121** [comment]
@binhonglee phew! You had me worried for a second there. I'll add an enhancement to throw up an error is maven is not installed. Thanks for contributing!
