### ISSUE TITLE
Failed to load the atom-maven package: uknown option

### ISSUE THREAD

**Issue by menelaosbgr** [concon121/atom-maven#87]
Installing atom-maven plugin results in an error.
Failed to load the atom-maven package: uknown option.

See information below:

> **Atom Version**: 1.0.3
> **System**: Microsoft Windows 7 Enterprise 
> **Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package, v1.3.0
> 
> 
> ### Stack Trace
> 
> Failed to load the atom-maven package
> 
> ```
> At [BABEL] C:\Users\bakopme\.atom\packages\atom-maven\lib\atom-maven.js: Unknown option: C:\Users\bakopme\.atom\packages\atom-maven\.babelrc.presets
> 
> ReferenceError: [BABEL] C:\Users\bakopme\.atom\packages\atom-maven\lib\atom-maven.js: Unknown option: C:\Users\bakopme\.atom\packages\atom-maven\.babelrc.presets
>     at Logger.error (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
>     at OptionManager.mergeOptions (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\options\option-manager.js:124:29)
>     at OptionManager.addConfig (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\options\option-manager.js:105:10)
>     at OptionManager.findConfigs (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\options\option-manager.js:166:35)
>     at OptionManager.init (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\options\option-manager.js:226:10)
>     at File.initOptions (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:154:75)
>     at new File (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:137:22)
>     at Pipeline.transform (C:\PGM\devel\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
>     at transpile (C:\PGM\devel\Atom\resources\app.asar\src\babel.js:128:16)
>     at Object.loadFile [as .js] (C:\PGM\devel\Atom\resources\app.asar\src\babel.js:165:67)
> ```
> 
> ### Commands
> 
> ```
>      -2:16.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
>   2x -2:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
> ```
> 
> ### Config
> 
> ```json
> {
>   "core": {}
> }
> ```
> 
> ### Installed Packages
> 
> ```coffee
> # User
> atom-maven, v1.3.0
> linter-javac, v1.7.0
> 
> # Dev
> No dev packages
> ```

**Comment by concon121** [comment]
Looks like an issue with babel, most likely you have the wrong version installed somewhere.  Do you get the same output as below when you run an npm list?

```
~/.atom/packages/atom-maven$ npm list --depth 0 | grep babel
├── babel@6.23.0
├── babel-cli@6.26.0
├── babel-core@6.26.0
├── babel-preset-es2015@6.24.1
├── babel-register@6.26.0
```
