### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Repositories/kbc/aem-provision/effecti...

### ISSUE THREAD

**Issue by bdhoine** [concon121/atom-maven#88]
[Enter steps to reproduce:]

1. install package
2. save maven pom file

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Barry/Repositories/kbc/aem-provision/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/Barry/Repositories/kbc/aem-provision/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -5:39.9.0 core:move-left (input.hidden-input)
     -5:39.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -5:35.4.0 editor:delete-to-beginning-of-line (input.hidden-input)
  2x -5:34.3.0 core:confirm (input.hidden-input)
  2x -4:06.5.0 core:backspace (input.hidden-input)
     -4:05.6.0 core:confirm (input.hidden-input)
     -2:53.5.0 settings-view:install-packages-and-themes (input.hidden-input)
     -2:48.2.0 core:confirm (input.hidden-input)
     -2:32.8.0 markdown-preview:toggle (input.hidden-input)
     -2:11.1.0 core:backspace (input.hidden-input)
  5x -2:10.2.0 core:confirm (input.hidden-input)
     -0:43.4.0 core:move-right (input.hidden-input)
     -0:41.5.0 core:save (input.hidden-input)
     -0:25.9.0 atom-maven:effectivePom (input.hidden-input)
  3x -0:14.7.0 core:close (input.hidden-input)
     -0:04.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-maven 1.3.0 
busy-signal 1.4.3 
intentions 1.1.2 
language-docker 1.1.8 
language-puppet 0.22.0 
linter 2.1.4 
linter-docker 0.2.0 
linter-puppet-lint 0.8.2 
linter-puppet-parser 0.1.1 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.0 
linter-vagrant-validate 1.1.0 
```

**Comment by bdhoine** [comment]
Looks like this won't be picked up
