### ISSUE TITLE
Uncaught Error: watch ~/Projects/NetBeansProjects/UtilProject/ ENOSPC

### ISSUE THREAD

**Issue by zygimantus** [concon121/atom-maven#89]
[Enter steps to reproduce:]

1. Trying to install it.

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: linux 4.11.7-1-ARCH
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: watch /home/zygimantus/Projects/UtilProject/ ENOSPC

```
At fs.js:1441

Error: watch /home/zygimantus/Projects/UtilProject/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Watcher.watchFile (/packages/atom-maven/node_modules/node-watch/lib/watch.js:281:20)
    at watch (/packages/atom-maven/node_modules/node-watch/lib/watch.js:399:13)
    at /packages/atom-maven/lib/atom-maven.js:104:9
    at didMatch (/build/atom/src/atom-1.18.0/out/app/src/workspace.js:1837:20)
    at /usr/lib/atom/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at ChildProcess.<anonymous> (/usr/lib/atom/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -8:20.9.0 intentions:highlight (input.hidden-input)
     -8:20.5.0 core:cut (input.hidden-input)
     -8:19.9.0 core:undo (input.hidden-input)
     -8:13.8.0 run-command:toggle-panel (input.hidden-input)
     -7:48.7.0 atom-beautify:beautify-editor (div.lines)
     -7:47.8.0 intentions:highlight (input.hidden-input)
     -7:47.6.0 core:undo (input.hidden-input)
  4x -6:15.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -5:46.9.0 intentions:highlight (input.hidden-input)
     -5:46.7.0 settings-view:open (input.hidden-input)
     -3:22.4.0 intentions:highlight (input.hidden-input)
     -3:22.2.0 core:copy (input.hidden-input)
     -3:22.1.0 intentions:highlight (input.hidden-input)
     -0:25.4.0 core:select-all (input.hidden-input)
  2x -0:19 core:backspace (input.hidden-input)
     -0:18.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-maven 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
git-plus 7.9.3 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.9 
minimap 4.28.2 
project-manager 3.3.5 
split-diff 1.4.3 
todo-show 1.11.0 
```

**Comment by concon121** [comment]
Please see issue #95
Shouldn't be trying to watch a directory though, will investigate further.
