### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Projects/nginx/plugins/packer/tmp/ecli...

### ISSUE THREAD

**Issue by akarasulu** [concon121/atom-maven#90]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/akarasulu/Projects/nginx/plugins/packer/tmp/eclipse/features/org.eclipse.rse.local_3.7.0.201610260947/META-INF/maven/org.eclipse.tm.features/org.eclipse.rse.local/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/akarasulu/Projects/nginx/plugins/packer/tmp/eclipse/features/org.eclipse.rse.local_3.7.0.201610260947/META-INF/maven/org.eclipse.tm.features/org.eclipse.rse.local/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -0:50.3.0 core:backspace (input.hidden-input)
     -0:42.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-maven 1.3.0 
busy-signal 1.4.3 
dash 1.7.1 
intentions 1.1.2 
language-jsonnet 0.1.0 
language-markdown 0.23.0 
linter 2.2.0 
linter-markdown 4.0.1 
linter-ui-default 1.6.2 
markdown-pdf 1.5.4 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
tidy-markdown 3.0.1 
tool-bar-markdown-writer 0.3.0 
```

**Comment by concon121** [comment]
Please ensure that eclipse metadata is in your .gitignore file. Please see issue #92 for further explanation.
