### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Downloads/Eclipse Installer.app/Conten...

### ISSUE THREAD

**Issue by aliyevnb** [concon121/atom-maven#92]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/aliyevn/Downloads/Eclipse Installer.app/Contents/Eclipse/features/org.eclipse.ecf.filetransfer.ssl.feature_1.1.0.v20170110-1317/META-INF/maven/org.eclipse.ecf/org.eclipse.ecf.filetransfer.ssl.feature/effective.pom'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/aliyevn/Downloads/Eclipse Installer.app/Contents/Eclipse/features/org.eclipse.ecf.filetransfer.ssl.feature_1.1.0.v20170110-1317/META-INF/maven/org.eclipse.ecf/org.eclipse.ecf.filetransfer.ssl.feature/effective.pom'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:49:29
    at /packages/atom-maven/node_modules/node-maven-api/lib/maven.js:71:7
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-dark-plus-ui 0.55.0 
atom-dark-solarized-ui 0.55.0 
atom-io-ui 0.1.0 
atom-light-ui-4k 0.30.1 
atom-material-ui 2.0.4 
atom-maven 1.3.0 
autocomplete-java 1.2.7 
autocomplete-python 1.9.1 
base64 0.3.0 
busy-signal 1.4.3 
git-plus 7.9.3 
intentions 1.1.2 
json-colorer 1.0.0 
json-converter 0.2.4 
linter 2.2.0 
linter-javac 1.9.4 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
monokai 0.24.0 
multi-cursor-plus 1.2.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
python-indent 1.1.0 
python-tools 0.6.9 
tree-view-git-status 1.4.0 
```

**Comment by concon121** [comment]
Looks like you have added eclipse metadata directories to your atom workspace. By default the Atom.workspace.scan api looks at everything in your workspace that is not git ignored. Please add your eclipse metadata to your .gitignore file to prevent the unnecessary effective pom being created and to avoid errors like these .
