### ISSUE TITLE
Uncaught Error: watch ~/projects/aries/cdi/ ENOSPC

### ISSUE THREAD

**Issue by rotty3000** [concon121/atom-maven#94]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [atom-maven](https://github.com/concon121/atom-maven) package 1.3.0

### Stack Trace

Uncaught Error: watch /home/rotty/projects/aries/cdi/ ENOSPC

```
At fs.js:1441

Error: watch /home/rotty/projects/aries/cdi/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Watcher.watchFile (/packages/atom-maven/node_modules/node-watch/lib/watch.js:281:20)
    at watch (/packages/atom-maven/node_modules/node-watch/lib/watch.js:399:13)
    at /packages/atom-maven/lib/atom-maven.js:104:9
    at didMatch (/usr/share/atom/resources/app/src/workspace.js:2126:28)
    at /usr/share/atom/resources/app/src/task.js:128:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app/src/task.js:80:40)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:39.9.0 editor:consolidate-selections (input.hidden-input)
     -0:39.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-maven 1.3.0 
```

**Comment by concon121** [comment]
ENOSPC indicates that the /tmp directory can't be written to, usually due to a lack of space.

See this SO post for more info:
https://stackoverflow.com/questions/22475849/node-js-error-enospc

Closing this issue as it is related to the user's system constraints which are outside of the control of atom-maven.
